### ISSUE TITLE
Event Detail Link Error

### ISSUE THREAD

**Issue by dalliard** [javebratt/event-tutorial#5]
When I copy an paste an Event Detail Link I get the following Error:

````
Error: Uncaught (in promise): TypeError: Cannot read property 'uid' of null
TypeError: Cannot read property 'uid' of null
...
````

Do you have a solution for that problem?

**Comment by javebratt** [comment]
Is the user currently logged in? Only logged in users can access the pages...

**Comment by dalliard** [comment]
The user is logged in. I open the detail of an event and the URL in the address bar looks like: 
http://localhost:8100/#/event-detail/-Khw_64hmQ0Y-fRTUnjV

When I open the link in a new tab I get the error from above.

**Comment by javebratt** [comment]
Are you using your own Firebase credentials or are you testing on my Firebase app?

**Comment by dalliard** [comment]
I tried both. With my own credentials and also with yours.

**Comment by javebratt** [comment]
Hmmm I just tested and worked fine on my end, are you trying an unmodified clone of this repo? Can I see it?

**Comment by dalliard** [comment]
I just `git clone`, `npm install` and `ionic serve`.

**Comment by javebratt** [comment]
It is weird, I'm running the code (_your link doesn't work for me for obvious reasons_) and it works without any trouble

**Comment by dalliard** [comment]
Hmm, really weird. Can you open http://localhost:8100/#/event-list when `ionic serve` is running on Port 8100? I mean the direct link. I get the error even there.

**Comment by javebratt** [comment]
Hmmm kinda, when I open a new browser window, that link loads then in removes the hash from the URL living it just like `http://localhost:8100/#/ but when I copy the URL in that browser window it loads fine.

**Comment by dalliard** [comment]
Hmm, right without the ID in the url it redirects to `http://localhost:8100/#/`, that seems to work. But with the ID in the url I still get the error, but it also redirects to `http://localhost:8100/#/`. I attached two Images, maybe that helps.

Sorry to bother you with this...
![2017-04-18-000951_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/25106773/9ed027a0-23cb-11e7-9963-da51c0e51e59.png)
![2017-04-18-001059_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/25106774/9ed81456-23cb-11e7-8922-926d931e5a76.png)

**Comment by javebratt** [comment]
Oh man, you're not bothering me, this helps me become a better developer, so thank you...

I found the problem, this app will need more work to be able to use dynamic linking, I'm going to implement this when I'm done updating the rest of the apps in the book to Ionic 3, but if you want to take a stab at it:

* The reason it's having the error is because it's trying to get the user synchronously since the app isn't running before entering from the link, the user returns null, then it fetches the user object and returns it, but our code is running with the null user.

* To fix that, in the `EventProvider` class, you can create a listener in the constructor:

```js
public userId:string;
constructor(){
  firebase.auth().onAuthStateChanged( user => {
    if(user) { this.userId = user.uid}
  });
}
```
Then replace all instances of `firebase.auth().currentUser.uid` with `this.userId`. That will take care of the problem. 

The other problem is the fact that it's redirecting to the `HomePage`, that happens because when the app is launching it directs to the event details page, but it triggers the `onAuthStateChanged()` that we have in `app.component.ts` which sends the user back to the `HomePage`, so we'll need to edit that listener to track when the user is coming from an URL just don't mess with the `rootPage` declaration :smile: 

Feel free to take a stab at it, or I will implement those changes next week.

Again, thank you for reporting, you helped me learn something new today :)
